import pytest
import numpy as np
import src.build_models as bm
import pandas as pd
import sklearn
from sklearn.ensemble import RandomForestClassifier

def test_happy_standardize_normalize():
    """
    Happy path to test the stan_norm function (that standardizes the input dataframe) in build_models.py
    Returns true if the actual output is the same as the expected output
    """
    train_df = pd.DataFrame([[40, 0, 2, 1, 2, 1, 1],
                             [72, 0, 0, 0, 1, 2, 2],
                             [20, 2, 10, 0, 1, 0, 0],
                              [86, 0, 1, 0, 2, 0, 3]],
                            columns=['age', 'sex', 'chest_pain',  'fasting_blood_sugar',\
                                     'electrocardiographic', 'induced_angina','thal'])

    test_df = pd.DataFrame([[170, 1, 1, 0, 0, 1, 1],
                             [56, 1, 3, 1, 0, 1, 3]],
                            columns=['age', 'sex', 'chest_pain', 'fasting_blood_sugar',\
                                     'electrocardiographic', 'induced_angina', 'thal'])

    train_df_fn, test_df_fn = bm.stan_norm(train_df, test_df)
    train_df_fn2 = round(pd.DataFrame(train_df_fn),6)
    test_df_fn2 = round(pd.DataFrame(test_df_fn),6)
    train_df_true = round(pd.DataFrame([[-0.55820864, -0.57735027, -0.3155972, 1.73205081, 1.,0.30151134, -0.4472136],
           [0.67370008, -0.57735027, -0.82055272, -0.57735027, -1.,1.50755672, 0.4472136],
           [-1.3281516, 1.73205081, 1.70422489, -0.57735027, -1.,-0.90453403, -1.34164079],
           [1.21266015, -0.57735027, -0.56807496, -0.57735027, 1.,-0.90453403, 1.34164079]]),6)

    test_df_true = round(pd.DataFrame([[4.44642056, 0.57735027, -0.56807496, -0.57735027, -3.,0.30151134, -0.4472136],
           [0.05774572, 0.57735027, -0.06311944, 1.73205081, -3.,0.30151134, 1.34164079]]),6)

    assert train_df_fn2.equals(train_df_true) and test_df_fn2.equals(test_df_true)

def test_unhappy_model():
    """
    Unhappy path to test if the model raises an error when the dependent variable is missing
    """
    train_df = pd.DataFrame([[40, 0, 2, 1, 2, 1, 1],
                             [72, 0, 0, 0, 1, 2, 2],
                             [20, 2, 10, 0, 1, 0, 0],
                              [86, 0, 1, 0, 2, 0, 3]],
                            columns=['age', 'sex', 'chest_pain',  'fasting_blood_sugar',\
                                     'electrocardiographic', 'induced_angina','thal'])

    columns_for_modeling = ['age', 'sex', 'chest_pain',  'fasting_blood_sugar',\
                                     'electrocardiographic', 'induced_angina','thal']

    target_column = 'diagnosis'

    with pytest.raises(SystemExit) as pytest_wrapped_e:
        features, target, temp = bm.split_features_target(train_df, target_column, columns_for_modeling)
    assert pytest_wrapped_e.type == SystemExit

def test_happy_model_obj_type():
    """
    Happy path to test if the correct object is generated by the modeling function
    """
    train_df = pd.DataFrame([[40, 0, 2, 1, 2, 1, 1],
                             [72, 0, 0, 0, 1, 2, 2],
                             [20, 2, 10, 0, 1, 0, 0],
                             [86, 0, 1, 0, 2, 0, 3]],
                            columns=['age', 'sex', 'chest_pain', 'fasting_blood_sugar', \
                                     'electrocardiographic', 'induced_angina', 'thal'])
    train_dep_var_df  = np.array([1, 1, 0, 0])

    model_obj = bm.rf_model(train_df,train_dep_var_df,n_estimators=10,max_depth=3)
    assert isinstance(model_obj, sklearn.ensemble.forest.RandomForestClassifier)

def test_unhappy_split_test_train():
    """
    Unhappy path to check if an error is thrown when the test_size is more than 1
    """
    features = pd.DataFrame([[40, 0, 2, 1, 2, 1, 1],
                             [72, 0, 0, 0, 1, 2, 2],
                             [20, 2, 10, 0, 1, 0, 0],
                              [86, 0, 1, 0, 2, 0, 3]],
                            columns=['age', 'sex', 'chest_pain',  'fasting_blood_sugar',\
                                     'electrocardiographic', 'induced_angina','thal'])

    target = pd.DataFrame([1,0,0,1],columns=['diagnosis'])

    with pytest.raises(SystemExit) as pytest_wrapped_e:
        X_train, X_test, y_train, y_test = bm.split_test_train(features, target, 1.2)
    assert pytest_wrapped_e.type == SystemExit